# Generated by Django 3.1.4 on 2020-12-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
